"""esquema inicial

Revision ID: a0e0619f35cf
Revises: 
Create Date: 2026-09-07 17:40:23.244429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a0e0619f35cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas_certificadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('peligroso', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=120), nullable=True),
    sa.Column('contacto_cargo', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion_servicio', sa.Text(), nullable=True),
    sa.Column('ciudad_servicio', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('condiciones_pago', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('tipo_interes', sa.String(length=30), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_telefono'), 'leads', ['telefono'], unique=False)
    op.create_table('manifiestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_generacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('fecha_recoleccion', sa.Date(), nullable=True),
    sa.Column('fecha_retorno', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('firma_cliente', sa.Boolean(), nullable=False),
    sa.Column('nombre_receptor', sa.String(length=120), nullable=True),
    sa.Column('cargo_receptor', sa.String(length=100), nullable=True),
    sa.Column('observaciones_campo', sa.Text(), nullable=True),
    sa.Column('observaciones_retorno', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('servicio_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('estado_antes', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=True),
    sa.Column('cambiado_por', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('cambiado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cambiado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declaraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('manifiesto_id', sa.Integer(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('fecha_certificacion', sa.Date(), nullable=True),
    sa.Column('numero_certificado', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['manifiesto_id'], ['manifiestos.id'], ),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas_certificadoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('factura_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tipo_residuo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['tipo_residuo_id'], ['tipos_residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifiesto_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifiesto_id', sa.Integer(), nullable=False),
    sa.Column('estado_antes', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=True),
    sa.Column('cambiado_por', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('cambiado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cambiado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['manifiesto_id'], ['manifiestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifiesto_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifiesto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_residuo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_declarada', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cantidad_real', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('descripcion_adicional', sa.Text(), nullable=True),
    sa.Column('numero_contenedor', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['manifiesto_id'], ['manifiestos.id'], ),
    sa.ForeignKeyConstraint(['tipo_residuo_id'], ['tipos_residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('medio_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento_cartera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_gestion', sa.String(length=50), nullable=True),
    sa.Column('fecha_gestion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('proxima_accion', sa.Text(), nullable=True),
    sa.Column('fecha_proxima', sa.Date(), nullable=True),
    sa.Column('gestionado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['gestionado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declaracion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaracion_id', sa.Integer(), nullable=False),
    sa.Column('manifiesto_item_id', sa.Integer(), nullable=True),
    sa.Column('tipo_residuo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['declaracion_id'], ['declaraciones.id'], ),
    sa.ForeignKeyConstraint(['manifiesto_item_id'], ['manifiesto_items.id'], ),
    sa.ForeignKeyConstraint(['tipo_residuo_id'], ['tipos_residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_tasks_contact_id', table_name='tasks')
    op.drop_index('idx_tasks_done', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks', postgresql_where='(due_date IS NOT NULL)')
    op.drop_table('tasks')
    op.drop_index('idx_notes_contact_id', table_name='notes')
    op.drop_index('idx_notes_created_at', table_name='notes')
    op.drop_table('notes')
    op.drop_index('idx_deals_contact_id', table_name='deals')
    op.drop_index('idx_deals_created_at', table_name='deals')
    op.drop_index('idx_deals_due_date', table_name='deals', postgresql_where='(due_date IS NOT NULL)')
    op.drop_index('idx_deals_stage', table_name='deals')
    op.drop_table('deals')
    op.drop_index('idx_contacts_created_at', table_name='contacts')
    op.drop_index('idx_contacts_status', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'media'::text"), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("priority = ANY (ARRAY['alta'::text, 'media'::text, 'baja'::text])", name='tasks_priority_check'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='tasks_contact_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False, postgresql_where='(due_date IS NOT NULL)')
    op.create_index('idx_tasks_done', 'tasks', ['done'], unique=False)
    op.create_index('idx_tasks_contact_id', 'tasks', ['contact_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='notes_contact_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notes_pkey')
    )
    op.create_index('idx_notes_created_at', 'notes', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_notes_contact_id', 'notes', ['contact_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'prospecto'::text"), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_contact', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['cliente'::text, 'prospecto'::text, 'lead'::text, 'inactivo'::text])", name='contacts_status_check'),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_contacts_status', 'contacts', ['status'], unique=False)
    op.create_index('idx_contacts_created_at', 'contacts', [sa.text('created_at DESC')], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.TEXT(), server_default=sa.text("'lead'::text"), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("to_char(now(), 'YYYY-MM-DD'::text)"), autoincrement=False, nullable=False),
    sa.Column('proposal_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invoice_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invoice_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('lost_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("payment_status = ANY (ARRAY['pagado'::text, 'parcial'::text, 'pendiente'::text])", name='deals_payment_status_check'),
    sa.CheckConstraint("stage = ANY (ARRAY['lead'::text, 'por-contactar'::text, 'contactado'::text, 'propuesta'::text, 'negociacion'::text, 'en-decision'::text, 'ganado'::text, 'perdido'::text, 'cerrado'::text])", name='deals_stage_check'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='deals_contact_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='deals_pkey')
    )
    op.create_index('idx_deals_stage', 'deals', ['stage'], unique=False)
    op.create_index('idx_deals_due_date', 'deals', ['due_date'], unique=False, postgresql_where='(due_date IS NOT NULL)')
    op.create_index('idx_deals_created_at', 'deals', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_deals_contact_id', 'deals', ['contact_id'], unique=False)
    op.drop_table('declaracion_items')
    op.drop_table('seguimiento_cartera')
    op.drop_table('pagos')
    op.drop_table('manifiesto_items')
    op.drop_table('manifiesto_historial')
    op.drop_table('lead_mensajes')
    op.drop_table('factura_items')
    op.drop_table('declaraciones')
    op.drop_table('servicio_historial')
    op.drop_table('manifiestos')
    op.drop_index(op.f('ix_leads_telefono'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('facturas')
    op.drop_table('servicios')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('tipos_residuo')
    op.drop_table('roles')
    op.drop_table('plantas_certificadoras')
    # ### end Alembic commands ###
